package tinybird

import (
	"net/url"
)

// Pipe is a object on tinybird, contains one or more SQL queries (Nodes) that
// result in either an API endpoint or a Materialized View.
type Pipe struct {
	// Name of pipe. Define by user.
	Name string
	// Is for internal purpose and is generated by code.
	URL string
	// Parameters use on pipe. Define by user.
	Parameters url.Values
	// Is an area that contains a set of Tinybird resources, including Pipes,
	// Nodes, APIs, Data Sources & Auth Tokens. Define by user.
	Workspace Workspace
}
